#!/usr/bin/env python
import sys, socket, argparse

# Global Variables
server_port = ('login-faculty.ccs.neu.edu', 3700)
basil_id = '001196523'
hussein_id = '001923995'

def _server_connect(host, port, neuid):
    s = socket.socket();
    findMyKey(s, host, port or 3700, neuid)

def findMyKey(socket, host, port, neuid):
    key = ''
    
    socket.connect((host, port or 3700))
    
    gotKey = False
    
    while not gotKey:
        received = socket.recv(1024)
        args = received.replace('\n', '').split(' ')
        if received == 'HELLO\n':
            reply = 'IAM ' + neuid + '\n'
            socket.send(reply)
        elif len(args) == 1:
             received = socket.recv(1024)
             reply = 'REPLY' + received
             socket.send(reply)
        elif args[0] == 'INFO':
            reply = 'REPLY ' + args[1] + '\n'
            socket.send(reply)
        elif args[0] == 'NULL':
            reply = 'REPLY ' + args[2] + '\n'
            socket.send(reply)
        elif args[0] == 'KEY':
            gotKey = True
            key = args[1]
        else:
            print 'ERROR - INVALID RESPONSE'
            break

    socket.close()
    print 'Key :', key 

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', help='port')
    parser.add_argument('HOSTNAME', help='hostname')
    parser.add_argument('NEUID', help='northeastern user id')
    args = parser.parse_args()

    _server_connect(args.HOSTNAME, args.p, args.NEUID)

main()
